//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Adderess_ID { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> Emp_ID { get; set; }
    
        public virtual Employee_Detials Employee_Detials { get; set; }
    }
}
