//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Emp_ID { get; set; }
        public Nullable<long> Salary_Amount { get; set; }
    
        public virtual Employee_Detials Employee_Detials { get; set; }
    }
}
